{{- if .Values.tlsSecret.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "argocd-agent-principal.tlsSecretName" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.tlsSecret.crt | b64enc | quote }}
  tls.key: {{ .Values.tlsSecret.key | b64enc | quote }}
{{- end }}