apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-agent-principal.grpcServiceName" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
  {{- with .Values.service.grpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.grpc.type }}
  {{- if and (eq .Values.service.grpc.type "LoadBalancer") .Values.service.grpc.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.grpc.loadBalancerIP }}
  {{- end }}
  ports:
  - name: https
    protocol: TCP
    port: {{ .Values.service.grpc.port }}
    targetPort: principal
  selector:
    {{- include "argocd-agent-principal.selectorLabels" . | nindent 4 }}