{{- if .Values.userpass.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-agent-principal.userpassSecretName" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
stringData:
  passwd: {{ .Values.userpass.passwd | quote }}
{{- end }}